# --------------- BACKEND --------------- 
backend:
 name: git-gateway
 branch: main

# --------------- MEDIA / IMAGES --------------- 
media_folder: "public/uploads"
public_folder: "/uploads"

# --------------- COLLECTIONS --------------- 
collections:
  - name: "portfolio"
    label: "Portfolio"
    label_singular: "Artwork"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string" 
        hint: "Name shown on the card and on the artwork page."

      # Date
      - label: "Date" 
        name: "date"
        widget: "datetime"
        format: "MMM DD YYYY"
        time_format: false
        hint: "Used for sorting. Pick the release/exhibition date."

      # Cover image and alt text 
      - label: "Cover image"
        name: "cover"
        widget: "image" 
        hint: "Main image. Recommended dimensions: 940x1268px (aspect ratio 3:4) for optimal display on the website"
      - label: "Cover image alt text"
        name: "coverAlt"
        widget: "string"
        hint: "Describe the image for accessibility (ex. 'Abstract painting with blue and gold tones', 'Sculpture of a blue rabbit made of ceramics')"

      # Link and link text
      - label: "Link URL"
        name: "link"
        widget: "string"
        required: false
        hint: "Optional link to external page (ex. exhibition page, press, etc.)"
      - label: "Link text"
        name: "linkText"
        widget: "string"
        required: false
        hint: "Link text shown on page (ex. 'Exhibition details', 'Gallery name ', etc.)"

      # Additional images (list)
      - label: "Additional images"
        name: "additionalImgs"
        widget: "list"
        required: false
        hint: "Additional gallery images (shown when going to the artwork/project page)."
        field:
          label: "Image"
          name: "image"
          widget: "image" 

      # Availability
      - label: "Available" 
        name: "available"
        widget: "boolean"
        default: false
        required: false
        hint: "Check this if the artwork is currently available for sale. It will show up on the 'Available Pieces' page."

      - label: "Available text" 
        name: "availableText"
        widget: "string"
        required: false
        hint: "Text overlay to display on 'Available Pieces page'. Keep it short and sweet!"

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "about"
    label: "About"
    label_singular: "AboutPost"
    folder: "src/content/about"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string" 
        hint: "Title shown on the about card/section"

      # Date
      - label: "Date" 
        name: "date"
        widget: "datetime"
        format: "MMM DD YYYY"
        time_format: false
        hint: "Used for sorting."

      # Cover image and alt text 
      - label: "Cover image"
        name: "cover"
        widget: "image" 
        hint: "Main image. Recommended dimensions: 940x1268px (aspect ratio 3:4) for optimal display on the website"
      - label: "Cover image alt text"
        name: "coverAlt"
        widget: "string"
        hint: "Describe the image for accessibility (ex. 'Abstract painting with blue and gold tones', 'Sculpture of a blue rabbit made of ceramics')"
      
      # Link
      - label: "Link URL"
        name: "link"
        widget: "string"
        required: false
        hint: "Optional link to external page (ex. exhibition page, press, etc.)"
     